### ISSUE TITLE
Error while --list-objects

### ISSUE THREAD

**Issue by prashanthbn** [jariq/Pkcs7SignatureGenerator#1]
I am getting error while listing objects stack trace:

```
Listing objects available on token with serial "0218e415" and label "eToken"
Operation error: Net.Pkcs11Interop.Common.Pkcs11Exception - Method C_GetAttributeValue returned 2164260865
   at Net.Pkcs11Interop.HighLevelAPI4.Session.GetAttributeValue(ObjectHandle objectHandle, List`1 attributes)
   at Net.Pkcs11Interop.HighLevelAPI.Session.GetAttributeValue(ObjectHandle objectHandle, List`1 attributes)
   at Net.Pkcs11Interop.HighLevelAPI.Session.GetAttributeValue(ObjectHandle objectHandle, List`1 attributes)
   at Pkcs7SignatureGenerator.Pkcs11Explorer.GetTokenObjects(Token token, Boolean login, String pin, List`1& privateKeys, List`1& certificates) in C:\Users\username\Desktop\Pkcs7SignatureGenerator\src\Pkcs7SignatureGenerator\Pkcs11Explorer.cs:line 133
   at Pkcs7SignatureGenerator.Program.Main(String[] args) in C:\Users\username\Desktop\Pkcs7SignatureGenerator\src\Pkcs7SignatureGenerator\Program.cs:line 285
```

**Comment by jariq** [comment]
This looks like error on the side of unamanaged PKCS#11 library / device because

> PKCS#11 function `C_GetAttributeValue` returned vendor specific error `0x81000001`.

You need to consult your device manual for more details or contact device vendor support.

BTW many PKCS#11 libraries support some kind of internal logging mechanism which may reveal the real cause of error. Exact steps needed to enable logging should be present in the documentation provided by the PKCS#11 library vendor.

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
